services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        ENVIRONMENT: ${ENVIRONMENT}  # Pass ENVIRONMENT variable to Dockerfile
    develop:
      watch:
        - action: sync
          path: ./website
          target: /app/website
          ignore:
            - website/node_modules
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: compose.yaml
        - action: sync+restart
          path: ./website/package.json
          target: /app/website/package.json
    ports:
      - "5173:5173"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=${ENVIRONMENT}
    volumes:
      - ./:/app  # Volume mount for dev mode
    # command: tail -f /dev/null  # Keep container running
  
  asp-net:
    build:
      context: .
      dockerfile: Dockerfile.aspnet
      args:
        ENVIRONMENT: ${ENVIRONMENT}  # Pass ENVIRONMENT
    ports:
      - "25052:25052"
    networks:
      - asp-mongodb
    secrets:
      - mongodb_credentials

  mongodb:
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    networks:
      - asp-mongodb
    ports:
      - '27017:27017'
    restart: always
    secrets:
      - mongodb_credentials
    volumes:
      - mongo-data:/data/db

networks:
  asp-mongodb:
    driver: bridge

secrets:
  mongodb_credentials:
    file: ./secrets/mongodb_credentials.secret

volumes:
  mongo-data:
