FROM node:lts-alpine AS build
WORKDIR /app/website

COPY website/package*.json ./
RUN npm ci

COPY website/. .
RUN npm run build

FROM nginx:alpine AS final
COPY infrastructure/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/website/dist /usr/share/nginx/html
EXPOSE 5173
